name: Deploy Airflow DAGS
on:
  push:
    branches: [main, dev]

jobs:
  get-vault-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Set branch-based environment variables
        uses: iamtheyammer/branch-env-vars@v1.1.3
        with:
          bevOverwrite: true
          DEPLOY_ENV: |
            main:go deployer en prod
            dev:go deployer en dev      

      - name: print
        run: echo "$DEPLOY_ENV"
