name: Deploy Airflow DAGS
on:
  push:
    branches: [main, dev]

env:
  DEPLOY_ENV: |
    main:go deployer en prod
    dev:go deployer en dev

jobs:
  get-vault-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: print
        run: echo "$DEPLOY_ENV"
