name: get_vault_creds

on:
  push:
    branches: main

jobs:
  login:
    runs-on: ubuntu-latest
    container:
      image: adeo-docker-adeo-software-factory-release.jfrog.io
      credentials:
        username: ${{ secrets.JFROG_USERNAME }}
        password: ${{ secrets.JFROG_TOKEN }}