# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  Get Vault Secret:
    container:
      name: 'adeo-docker-adeo-software-factory-release.jfrog.io/vault/vault-ci:latest'
    artifacts:
      paths:
        - vault.token.enc
        - vault-ci-tools/
      expire_in: "600"
    script:
      - ./build
    