name: get_vault_creds

on:
  push:
    branches: main

jobs:
  vault:
    runs-on: ubuntu-latest
    container:
      image: adeo-docker-adeo-software-factory-release.jfrog.io/vault/vault-ci:latest
      credentials:
        username: ${{ secrets.JFROG_USERNAME }}
        password: ${{ secrets.JFROG_TOKEN }}

    steps:
      - name: machine ls $GITHUB_EVENT_PATH
        run: "ls -la $GITHUB_EVENT_PATH"
      - name: machine ls $GITHUB_WORKSPACE
        run: "ls -la $GITHUB_WORKSPACE"
      - name: machine ls $HOME
        working-directory: "."
        run: "ls -la $HOME/root"