name: get_vault_creds

on:
  push:
    branches: main

jobs:
  vault:
    runs-on: ubuntu-latest

    container:
      image: adeo-docker-adeo-software-factory-release.jfrog.io/vault/vault-ci:latest
      credentials:
        username: ${{ secrets.JFROG_USERNAME }}
        password: ${{ secrets.JFROG_TOKEN }}

    steps:
      - name: machine ls $GITHUB_EVENT_PATH
        run: "ls"
        env:
          DEV_PROJECT_ID: "didd-trnsvers-dev-dip"
          PROD_PROJECT_ID: "didd-transvers-prd-dip"
          DEV_CREDENTIALS: "dev/service_account"
          DEV_MODULE: "dev/vault_module"
          PROD_CREDENTIALS: "prod/service_account"
          PROD_MODULE: "prod/vault_module"
          VAULT_SECRET_PATH: "${DEV_CREDENTIALS},${PROD_CREDENTIALS},${DEV_MODULE},${PROD_MODULE}"
          VAULT_NAMESPACE: "adeo/DigitalIndustryDataDriven-Transverse"