name: Test
on:
  push:
    branches: dev

defaults:
  run:
    shell: bash
    working-directory: .

jobs:
  deploy:
    runs-on: [self-hosted, Linux, standard]

    steps:
      - name: Ping ext
        run: ping 104.155.74.0 -t 4
        
      - name: Ping pub
        run: ping 172.16.0.34 -t 4

      - name: Override Airflow configuration
        run: gcloud composer environments run $COMPOSER_ENV --location=$REGION variables import -- "/home/airflow/gcs/data/$AIRFLOW_CONFIG_FILE"
