name: get_vault_creds

on:
  push:
    branches: main

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to JFrog
        uses: docker/login-action@v2
        with:
          registry: adeo-docker-adeo-software-factory-release.jfrog.io
          username: ${{ dev.JFROG_USERNAME }}
          password: ${{ dev.JFROG_TOKEN }}